import sqlite3
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

def plot_ntp_research():
    try:
        # Connect to the DB generated by your Docker nodes
        conn = sqlite3.connect('research_data.db')
        df = pd.read_sql_query("SELECT * FROM ntp_metrics", conn)
        conn.close()

        if df.empty:
            print("No data found yet. Let the containers run for a minute!")
            return

        # Convert timestamp strings to actual datetime objects
        df['recorded_at'] = pd.to_datetime(df['recorded_at'])

        plt.figure(figsize=(12, 6))
        
        # Plot a line for each unique Docker node
        for node in df['node_id'].unique():
            node_data = df[df['node_id'] == node]
            plt.plot(node_data['recorded_at'], node_data['offset_sec'], marker='.', label=f"Node: {node[:8]}")

        plt.title('Precision Time Stamping: Offset Scaling Test (5 Nodes)', fontsize=14)
        plt.xlabel('Time of Collection', fontsize=12)
        plt.ylabel('Offset from Server (Seconds)', fontsize=12)
        plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
        plt.grid(True, linestyle='--', alpha=0.6)
        
        # Formatting the X-axis for time
        plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%H:%M:%S'))
        plt.gcf().autofmt_xdate()
        
        plt.tight_layout()
        print("Displaying graph... Close the window to stop.")
        plt.show()

    except Exception as e:
        print(f"Error plotting data: {e}")
        print("Note: You might need to install pandas and matplotlib: pip install pandas matplotlib")

if __name__ == "__main__":
    plot_ntp_research()